#!/usr/bin/env python

import rospy

import message_filters
from geometry_msgs.msg import Vector3Stamped, TwistStamped, TwistWithCovarianceStamped
from sensor_msgs.msg import Imu

rospy.init_node("message_filter")

imu_pub = rospy.Publisher("imu/data_raw", Imu, queue_size=5)
odom_pub = rospy.Publisher("wheel_odom_with_covariance", TwistWithCovarianceStamped, queue_size=5)
imu_msg = Imu()
odom_msg = TwistWithCovarianceStamped()

odom_msg.twist.covariance[0] = rospy.get_param("~wheel_odom_linear_variance")
odom_msg.twist.covariance[35] = rospy.get_param("~wheel_odom_angular_variance")

imu_ang_vel_cov = rospy.get_param("~imu_angular_velocity_covariance_diagonal")
imu_lin_acc_cov = rospy.get_param("~imu_linear_acceleration_covariance_diagonal")

imu_msg.angular_velocity_covariance[0] = imu_ang_vel_cov[0]
imu_msg.angular_velocity_covariance[3] = imu_ang_vel_cov[1]
imu_msg.angular_velocity_covariance[6] = imu_ang_vel_cov[2]

imu_msg.linear_acceleration_covariance[0] = imu_lin_acc_cov[0]
imu_msg.linear_acceleration_covariance[3] = imu_lin_acc_cov[1]
imu_msg.linear_acceleration_covariance[6] = imu_lin_acc_cov[2]

def imu_callback(gyro, accel):
    imu_msg.header.stamp = gyro.header.stamp
    imu_msg.header.frame_id = gyro.header.frame_id

    imu_msg.angular_velocity = gyro.vector
    imu_msg.linear_acceleration = accel.vector

    imu_pub.publish(imu_msg)

def odom_callback(odom):
    odom_msg.header.stamp = odom.header.stamp
    odom_msg.twist.twist = odom.twist

    odom_pub.publish(odom_msg)

rospy.wait_for_message("imu/gyro", Vector3Stamped)

gyro_sub = message_filters.Subscriber('imu/gyro', Vector3Stamped)
accel_sub = message_filters.Subscriber('imu/accel', Vector3Stamped)
odom_sub = rospy.Subscriber("wheel_odom", TwistStamped, odom_callback)

ts = message_filters.TimeSynchronizer([gyro_sub, accel_sub], 5)
ts.registerCallback(imu_callback)

rospy.spin()